apiVersion: v1
kind: Pod
metadata:
  name: corefinance
  labels:
    app.kubernetes.io/name: corefinance
spec:
  containers:
    - name: userprofile-service-1
      image: corefinance-userprofile1:latest
      command: ['/app/run_java_app.sh']
    - name: userprofile-service-2
      image: corefinance-userprofile2:latest
      command: ['/app/run_java_app.sh']