server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:core_finance_product}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: ${DB_MAX_CONNECTIONS:10}
      minimum-idle: ${DB_MIN_CONNECTIONS:2}
      idle-timeout: 30000
      pool-name: product_service_pool

management:
  server:
    port: ${server.port}