
server.port: 8087

spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:5432};databaseName=${DB_NAME:core_finance_payment}
    username: ${DB_USER:sbrsApp}
    password: ${DB_PASS:D3f@ultPwd#8}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: ${DB_MAX_CONNECTIONS:10}
      minimum-idle: ${DB_MIN_CONNECTIONS:2}
      idle-timeout: 30000
      pool-name: payment_service_pool

management:
  server:
    port: ${server.port}
