#Logging
logging.config: classpath:logback.xml

spring:
  profiles.active: dev
  main:
    allow-bean-definition-overriding: false
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true
      write-date-keys-as-timestamps: true
      write-durations-as-timestamps: true
      write-enums-using-to-string: false
      FAIL_ON_EMPTY_BEANS: false
  jackson-custom:
    serialization:
      local-date-format: yyyy-MM-dd
      local-time-format: hh:mm:ss
      zoned-date-time-format: yyyy-MM-dd'T'HH:mm:ss.SSSX
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
      show-sql: true
      generate-ddl: false
  # Liquibase settings
  liquibase:
    change-log: classpath:db/changelog/sql-changelog.xml
    drop-first: false
    enabled: true
    contexts: development
tech:
  corefinance:
    app:
      converter:
        local-date-to-string: true
        local-date-time-to-string: true
        zoned-date-time-to-string: true
        zoned-date-time-to-local-date-time: true
        zoned-date-time-to-date: true
      userprofile:
        default-password-authen: true
        enable-index-controller: true
    common:
      filter-ordered:
        authen-filter: 2
        tenant-id-filter-order: 3
        trace-info-id-order: 1
        encoding-response-order: 0
      enabled:
        async: true
        simple-version: true
        property-encryption: true
        auto-response-encoding: true
        trace-id-filter: true
        tenant: true
      default-response-charset: utf-8
      generic-exception-handling: true
    log:
      enabled:
        services: true
        repositories: true
        api: true
    security:
      internal-api-key: No-key
      # Json Web Token
      jwt:
        expiration: 3600
        login-mode: SINGLE_LOGIN_PER_APP
        enabled:
          common: true
        max-login-fail-allowed: 3
      public-key: classpath:public_key.der
      no-authen-urls:
        - /
        - /index
        - /void
        - /parserConfigurationException
        - /throwable
        - /test/api/*
      permission:
        default-control: ALLOWED
      authorize-check: true
      scan-controllers-actions: true
      ignore-controller-scan:
        - .springframework.
        - .springdoc.
        - .test.
      url-cors:
        cors-configurations:
          - url-pattern: /v3/api-docs/*
            allowed-origins:
              - http://localhost:4200
            allowed-methods:
              - GET
            allowed-headers: '*'
          - url-pattern: /**
            allowed-origins: '*'
            allowed-methods:
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - POST
              - PATCH
            allowed-headers: '*'
    schema-tenancy:
      mode: postgresql
      ignore-schemas:
        - public
        - test_schema
      enabled: true
      schema-prefix: tenant_
      default-schema: public
    audit:
      enabled:
        zoned-date-time: true
        basic-user: true
        delete-track: true
export:
  format:
    date: yyyy/MM/dd
    datetime: yyyy/MM/dd HH:mm:ss
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:password}
    #algorithm: PBEWithHmacSHA512AndAES_256
    algorithm: PBEWithMD5AndTripleDES
    #salt-generator-class-name: org.jasypt.salt.ZeroSaltGenerator
    salt-generator-class-name: org.jasypt.salt.RandomSaltGenerator
    #iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    # provider-class-name: com.sun.crypto.provider.SunJCE
    provider-name: SunJCE
    string-output-type: base64
    key-obtention-iterations: 1000
    pool-size: 1
    proxy-property-sources: false
    # skip-property-sources:

management:
  endpoints:
    web:
      base-path: /actuator
      enabled: true
      exposure.include: '*'